server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.105.101:3306/user-manage?serverTimezone=GMT%2b8
    username: roydon
    password: roydon#Mysql
  servlet:
    multipart:
      max-file-size: 20MB # 默认1MB
      enabled: true
      max-request-size: 200MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
files:
  upload:
    #    path: /home/files/
    path: D:/home/userManage/
